# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\create_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProjectDialog(object):
    def setupUi(self, CreateProjectDialog):
        CreateProjectDialog.setObjectName("CreateProjectDialog")
        CreateProjectDialog.resize(330, 147)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateProjectDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 110, 281, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.hourlyRate = QtWidgets.QLineEdit(CreateProjectDialog)
        self.hourlyRate.setGeometry(QtCore.QRect(20, 80, 291, 20))
        self.hourlyRate.setObjectName("hourlyRate")
        self.projectName = QtWidgets.QLineEdit(CreateProjectDialog)
        self.projectName.setGeometry(QtCore.QRect(20, 30, 291, 20))
        self.projectName.setObjectName("projectName")
        self.label_2 = QtWidgets.QLabel(CreateProjectDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 379, 20))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(CreateProjectDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 461, 16))
        self.label.setObjectName("label")

        self.retranslateUi(CreateProjectDialog)
        self.buttonBox.accepted.connect(CreateProjectDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(CreateProjectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CreateProjectDialog)
        CreateProjectDialog.setTabOrder(self.projectName, self.hourlyRate)

    def retranslateUi(self, CreateProjectDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateProjectDialog.setWindowTitle(_translate("CreateProjectDialog", "Nouveau projet"))
        self.label_2.setText(_translate("CreateProjectDialog", "Tarif horaire"))
        self.label.setText(_translate("CreateProjectDialog", "Nom du projet"))
