# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\edit_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_EditProjectDialog(object):
    def setupUi(self, EditProjectDialog):
        EditProjectDialog.setObjectName("EditProjectDialog")
        EditProjectDialog.resize(330, 205)
        self.buttonBox = QtWidgets.QDialogButtonBox(EditProjectDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 170, 281, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.hourlyRate = QtWidgets.QLineEdit(EditProjectDialog)
        self.hourlyRate.setGeometry(QtCore.QRect(20, 80, 291, 20))
        self.hourlyRate.setObjectName("hourlyRate")
        self.projectName = QtWidgets.QLineEdit(EditProjectDialog)
        self.projectName.setGeometry(QtCore.QRect(20, 30, 291, 20))
        self.projectName.setObjectName("projectName")
        self.label_2 = QtWidgets.QLabel(EditProjectDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 379, 20))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(EditProjectDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 461, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(EditProjectDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 291, 16))
        self.label_3.setObjectName("label_3")
        self.elapsedHours = QtWidgets.QLineEdit(EditProjectDialog)
        self.elapsedHours.setGeometry(QtCore.QRect(20, 130, 71, 20))
        self.elapsedHours.setObjectName("elapsedHours")
        self.elapsedMinutes = QtWidgets.QLineEdit(EditProjectDialog)
        self.elapsedMinutes.setGeometry(QtCore.QRect(120, 130, 71, 20))
        self.elapsedMinutes.setObjectName("elapsedMinutes")
        self.elapsedSeconds = QtWidgets.QLineEdit(EditProjectDialog)
        self.elapsedSeconds.setGeometry(QtCore.QRect(220, 130, 71, 20))
        self.elapsedSeconds.setObjectName("elapsedSeconds")
        self.label_4 = QtWidgets.QLabel(EditProjectDialog)
        self.label_4.setGeometry(QtCore.QRect(100, 130, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(EditProjectDialog)
        self.label_5.setGeometry(QtCore.QRect(200, 130, 16, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(EditProjectDialog)
        self.label_6.setGeometry(QtCore.QRect(300, 130, 16, 16))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(EditProjectDialog)
        self.buttonBox.accepted.connect(EditProjectDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EditProjectDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditProjectDialog)
        EditProjectDialog.setTabOrder(self.projectName, self.hourlyRate)

    def retranslateUi(self, EditProjectDialog):
        _translate = QtCore.QCoreApplication.translate
        EditProjectDialog.setWindowTitle(_translate("EditProjectDialog", "Éditer le projet"))
        self.label_2.setText(_translate("EditProjectDialog", "Tarif horaire"))
        self.label.setText(_translate("EditProjectDialog", "Nom du projet"))
        self.label_3.setText(_translate("EditProjectDialog", "Temps passé"))
        self.label_4.setText(_translate("EditProjectDialog", "h"))
        self.label_5.setText(_translate("EditProjectDialog", "m"))
        self.label_6.setText(_translate("EditProjectDialog", "s"))
